[project]
name = "minimdo"
version = "0.0.2"
authors = [
  { name="Johannes Norheim", email="norheim@mit.edu" },
]
description = "A small example package"
readme = "README.md"
requires-python = ">=3.7"
